spring: 
 datasource:
  url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
  driverClassName: org.h2.Driver
  username: sa
  password: 
  initialization-mode: embedded
 jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  properties:
   hibernate:
    generate_statistics: false
    format_sql: true
    ddl-auto: none
    show_sql: true
 h2:
  console: 
   enabled: true
eureka:
    instance:
      hostname: localhost
    client:
      registerWithEureka: false
      fetchRegistry: false
server:
  port : 8082
  
  

  
 